env = 'TestNet'
algod_url = "http://localhost:4001"
algod_token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
indexer_url = "http://localhost:8980"
indexer_token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
app_id = 339
wallet_id = "wallet_QWEASD"
account_a_address = "2WR5BCIVNEHTOPZA3DKEVS4YSCRBSU3FFNGTEPMEETVX524VXBI5OEV4DA"
account_a_mnemonic = "suit useful sell stumble rebel void during barrel market view shock fiscal rifle forward enrich tide lemon talk leaf also artwork crunch denial about crime"
account_b_address = ""
account_b_mnemonic = ""
account_c_address = ""
account_c_mnemonic = ""